[package]
name    = "mesh-apis"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
mt = ["sylvia/mt"]

[dependencies]
cosmwasm-std     = { workspace = true }
cosmwasm-schema  = { workspace = true }
schemars         = { workspace = true }
semver           = { workspace = true }
serde            = { workspace = true }
sylvia           = { workspace = true }
thiserror        = { workspace = true }
